Make kubeconfig file writable
We are facing an error when invoking kind within the container:
```
 ...

  ✓ Installing StorageClass 💾
  ✓ Waiting ≤ 3m0s for control-plane = Ready ⏳
  • Ready after 15s 💚
 ERROR: failed to create cluster: failed to write KUBECONFIG: open /config/8041fbc5: read-only file system

 ...
```

Make a copy of the original file and bind it in the container,
read-write, so that changes made within the container doesn't affect the
original one.